import type { AnalysisHistoryItem } from "./dashboard-types";

/**
 * Mock analysis history. Replace with a server fetch when the API is ready.
 * Thumbnails reuse the existing /public/dash assets.
 */
export const analysisHistory: AnalysisHistoryItem[] = [
  {
    id: "a1",
    title: "Financial Wisdom",
    note: "Strong advice. Needs CTA",
    thumbnail: "/dash/video1.png",
    duration: "00:45",
    status: "completed",
    date: "2024-05-20",
    time: "10:30 AM",
  },
  {
    id: "a2",
    title: "5 Tips to Grow Faster",
    note: "Good hook. Improve pacing in middle",
    thumbnail: "/dash/video2.png",
    duration: "01:02",
    status: "completed",
    date: "2024-05-18",
    time: "04:15 PM",
  },
  {
    id: "a3",
    title: "A Day in the Mountains",
    note: "Great visuals. Add stronger CTA",
    thumbnail: "/dash/video4.png",
    duration: "00:30",
    status: "completed",
    date: "2024-05-15",
    time: "09:45 AM",
  },
  {
    id: "a4",
    title: "Morning Routine",
    note: "Engaging start. Good structure",
    thumbnail: "/dash/video6.png",
    duration: "00:51",
    status: "completed",
    date: "2024-05-12",
    time: "08:20 PM",
  },
  {
    id: "a5",
    title: "Content Ideas That Work",
    note: "Solid content. Boost hook strength",
    thumbnail: "/dash/video5.png",
    duration: "00:47",
    status: "completed",
    date: "2024-05-10",
    time: "11:05 AM",
  },
  {
    id: "a6",
    title: "My Content Studio Setup",
    note: "Clear walkthrough. Trim intro",
    thumbnail: "/dash/video2.png",
    duration: "01:12",
    status: "completed",
    date: "2024-05-08",
    time: "02:40 PM",
  },
  {
    id: "a7",
    title: "Stop Making This Mistake",
    note: "Strong hook. Great retention",
    thumbnail: "/dash/video3.png",
    duration: "00:59",
    status: "completed",
    date: "2024-05-06",
    time: "06:10 PM",
  },
  {
    id: "a8",
    title: "Behind the Scenes",
    note: "Authentic tone. Add captions",
    thumbnail: "/dash/video1.png",
    duration: "00:38",
    status: "completed",
    date: "2024-05-04",
    time: "01:25 PM",
  },
  {
    id: "a9",
    title: "How I Plan My Week",
    note: "Useful tips. Tighten ending",
    thumbnail: "/dash/video6.png",
    duration: "01:05",
    status: "completed",
    date: "2024-05-02",
    time: "09:00 AM",
  },
  {
    id: "a10",
    title: "Top 3 Editing Tricks",
    note: "Actionable. Strong pacing",
    thumbnail: "/dash/video3.png",
    duration: "00:52",
    status: "completed",
    date: "2024-04-29",
    time: "03:50 PM",
  },
  {
    id: "a11",
    title: "Why Consistency Wins",
    note: "Motivational. Add example",
    thumbnail: "/dash/video5.png",
    duration: "00:44",
    status: "completed",
    date: "2024-04-27",
    time: "10:15 AM",
  },
  {
    id: "a12",
    title: "Lakeside Reflections",
    note: "Beautiful shots. Slow start",
    thumbnail: "/dash/video4.png",
    duration: "00:33",
    status: "completed",
    date: "2024-04-25",
    time: "07:30 AM",
  },
  {
    id: "a13",
    title: "Build Your Brand",
    note: "Great structure. Stronger CTA",
    thumbnail: "/dash/video1.png",
    duration: "01:18",
    status: "completed",
    date: "2024-04-22",
    time: "05:05 PM",
  },
  {
    id: "a14",
    title: "Quick Productivity Hack",
    note: "Punchy. Reduce text on screen",
    thumbnail: "/dash/video2.png",
    duration: "00:28",
    status: "completed",
    date: "2024-04-20",
    time: "12:45 PM",
  },
  {
    id: "a15",
    title: "Storytelling 101",
    note: "Compelling. Add b-roll",
    thumbnail: "/dash/video3.png",
    duration: "01:09",
    status: "completed",
    date: "2024-04-18",
    time: "08:55 AM",
  },
  {
    id: "a16",
    title: "Travel Day Vlog",
    note: "Fun energy. Trim mid-section",
    thumbnail: "/dash/video4.png",
    duration: "01:30",
    status: "completed",
    date: "2024-04-15",
    time: "06:20 PM",
  },
  {
    id: "a17",
    title: "Grow on Social Fast",
    note: "Strong value. Improve thumbnail",
    thumbnail: "/dash/video5.png",
    duration: "00:55",
    status: "completed",
    date: "2024-04-13",
    time: "11:40 AM",
  },
  {
    id: "a18",
    title: "Desk Tour 2024",
    note: "Clean visuals. Add product links",
    thumbnail: "/dash/video6.png",
    duration: "01:01",
    status: "completed",
    date: "2024-04-11",
    time: "04:00 PM",
  },
  {
    id: "a19",
    title: "Hook Writing Formula",
    note: "Very practical. Great pacing",
    thumbnail: "/dash/video1.png",
    duration: "00:49",
    status: "completed",
    date: "2024-04-09",
    time: "09:30 AM",
  },
  {
    id: "a20",
    title: "Editing My First Reel",
    note: "Helpful. Show timeline closer",
    thumbnail: "/dash/video2.png",
    duration: "01:14",
    status: "completed",
    date: "2024-04-07",
    time: "02:10 PM",
  },
  {
    id: "a21",
    title: "Mindset for Creators",
    note: "Inspiring. Tighten intro",
    thumbnail: "/dash/video3.png",
    duration: "00:41",
    status: "completed",
    date: "2024-04-05",
    time: "07:50 AM",
  },
  {
    id: "a22",
    title: "Sunset Timelapse",
    note: "Stunning. Add music swell",
    thumbnail: "/dash/video4.png",
    duration: "00:25",
    status: "completed",
    date: "2024-04-03",
    time: "06:45 PM",
  },
  {
    id: "a23",
    title: "Repurpose Your Content",
    note: "Smart strategy. Strong CTA",
    thumbnail: "/dash/video5.png",
    duration: "01:07",
    status: "completed",
    date: "2024-04-01",
    time: "10:05 AM",
  },
  {
    id: "a24",
    title: "Evening Wind Down",
    note: "Calm tone. Good structure",
    thumbnail: "/dash/video6.png",
    duration: "00:58",
    status: "completed",
    date: "2024-03-29",
    time: "08:35 PM",
  },
];
